---
stages:
- name: Build
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: dist
    build_type: shell
    script: |-
      #!/bin/bash
      export NPM_PACKAGES=~/.npm_packages
      echo prefix=$NPM_PACKAGES >> ~/.npmrc
      mkdir $NPM_PACKAGES

      export PATH=$NPM_PACKAGES/bin:$PATH

      npm install npm@2.14.4 -g
      $NPM_PACKAGES/bin/npm install
      grunt
- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |
      #!/bin/bash
      cf push "${CF_APP}"

      # view logs
      #cf logs "${CF_APP}" --recent
